name: gateway CI/CD

on:
  push:
    branches: [ "main" ]

#defaults:
  #run:
    #working-directory: ./gateway/

jobs:
  build:
    # runner for the job
    runs-on: ubuntu-latest 
    steps:
    # get the code
    - name: checkout
      uses: actions/checkout@v4.1.7
    # install nodejs
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 20.x
    # install the gateway's dependencies
    - name: npm install
      run: npm install
      working-directory: ./gateway/
    # build the gateway code
    - name: npm build
      run: npm run build
      working-directory:  ./gateway/
      
  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./gateway/
    steps:
      # verify the current working directory
      - name: pwd and ls
        run: pwd && ls -lhp
      # run all the jest tests
      - name: run all tests
        run: npm run test
