name: post micro-service CI/CD

on:
  push:
    # Trigger this workflow after a new commit has been pushed on branch feature/authentication-jwt
    branches: [ "feature/authentication-jwt" ]

defaults:
  run:
    working-directory: ./post/

jobs:
  build:
    # Runner for the job
    runs-on: ubuntu-latest 
    # Docker Hub image that the job executes in
    container: node:20
    steps:
    # Get the code, as is on the branch feature/authentication-jwt
    - name: Checkout the code
      uses: actions/checkout@v4.1.7
    - name: Install the post micro-service's dependencies
      run: npm install
    - name: Build the post micro-service
      run: npm run build
    - name: Cache the compiled post micro-service files
      id: cache-post
      uses: actions/cache@v4
      with:
        path: ./post/
        key: post-${{ github.ref_name }}-${{ github.sha }}
      
  unit-tests:
    # The build job must have finished successfuly before starting this job
    needs: build
    # GitHub environment (providing vars and secrets) to be used during the job
    environment: dev
    runs-on: ubuntu-latest
    container: node:20
    # Service containers to run with the job
    services:
        # Label used to access the service container
        post_database:
            # Docker Hub image
            image: mariadb:latest
            ports:
                - 3307:3306
            # Provide the credentials and other info for mariadb
            env:
                MARIADB_ROOT_PASSWORD: ${{ secrets.POST_MARIADB_ROOT_PASSWORD }}
                MARIADB_USER: ${{ vars.POST_MARIADB_USER }}
                MARIADB_PASSWORD: ${{ secrets.POST_MARIADB_PASSWORD }}
                MARIADB_DATABASE: ${{ vars.POST_MARIADB_DATABASE }}

    steps:
      ## Get the code, as is on the branch feature/authentication-jwt
      #- name: Checkout the code
        #uses: actions/checkout@v4.1.7
      #- name: Install the post micro-service's dependencies
        #run: npm install
      - name: Restore all the post micro-service files
        #id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: ./post/
          key: post-${{ github.ref_name }}-${{ github.sha }}
      - name: Run all the jest tests for post
        run: npm run test
        env:
          INIT_DB_WITH_MOCK: ${{ vars.INIT_DB_WITH_MOCK }}
